version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - ${DB_FORWARD_PORT:-5432}:5432
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD:-postgres}  # Default to 'postgres' if not set
      POSTGRES_USER: ${POSTGRES_USER:-postgres}  # Default to 'postgres' if not set
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_default_password}  # Set a default password
      POSTGRES_DB: ${POSTGRES_DATABASE:-your_default_database}  # Set a default database name
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - ${ADMINER_PORT:-8080}:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data: